# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Oblivious"
description: > # this means to ignore newlines until "email:"
   <s>Wilson's</s> Blog

email: wilcohol@gmail.com
#blog logo
logo: "/assets/images/w.png"
# blog cover
cover: "/assets/images/11944074014_c7c7e359db_o.jpg"

name: 'Wilson Ngu'
author: 'Wilson Ngu'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://notwilson.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@notwilson'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/notwilson
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/notwilson
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
